{% set name = "abi-dumper" %}
{% set version = "1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lvc/abi-dumper/archive/refs/tags/{{ version }}.tar.gz
  sha256: aa7a52bf913ab1a64743551d64575f921df3faa4a592a0f6614e047bc228708a

build:
  number: 0
  skip: true  # [not linux]
  script:
    - sed -i "s|#!/usr/bin/perl|#!$PREFIX/bin/perl|" abi-dumper.pl
    - make install prefix=$PREFIX

requirements:
  build:
    - make
  host:
    - perl >=5.8
  run:
    - {{ compiler('cxx') }}
    - binutils
    - elfutils
    - perl >=5.8
    - universal-ctags
    - vtable-dumper >=1.1

test:
  commands:
    - abi-dumper --help

about:
  home: https://github.com/lvc/abi-dumper
  summary: 'Dump ABI of an ELF object containing DWARF debug info'
  description: >
    ABI Dumper — a tool to dump ABI of an ELF object containing DWARF debug info.

    The tool is intended to be used with ABI Compliance Checker tool for tracking ABI changes of a C/C++ library or kernel module: https://github.com/lvc/abi-compliance-checker

    The tool is developed by Andrey Ponomarenko.
  license: LGPL-2.1-or-later
  license_file: LICENSE
  dev_url: https://github.com/lvc/abi-dumper

extra:
  recipe-maintainers:
    - carterbox
